dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: vBwSwdjpuxvCA1C6XNMuvuZq0DZEL0mXWC9VlkRNMAU9bjMdP6/uAdSGenuymI3dqKbfxjFRmJQ2WMvN7plQp2Z1MfKtSmAPauqRbB5HqHtOWRG44oi0aP7kWYYVPOdBg7ANoABacD50cLymQ49BffTHYoAPaJ+iXy85hsmg3ALjAJBKzMXC1eMQu/JDausraJYfktcLOh8l+z3WSdAP6yLbQKVMfsCjfOmcirBONBG480EznVc5e7xx9o1pWJ8xq/4E/WKoL+aLncphB8DEEYoiRbD6kPhjf9I1sSsfUXnBpY1L+8bAP82fVQj9eyR4N6/EuHBmaXeZcFew8z3Hv3rpL2EuVZPp6aGsL1rgVNiMmFdtjMx9Zp92l12KW6/M4teGSfrjXeRPKuOO2Y8ERf9sLK7owlklLDWj9SlTyQM2TXqjO1xJ5uK8aF2YxviyiuEyWCAZDabVz6VjS8l2C18MmjjCA7789HYs8FPCqV13XYzdHXSw9Pf9wjJthznv4BRckUFgT4Qg8QQ4AbXze62QxBvW28NXSMYgE0SUh0G7zsFZff4BL02UPtmd0eWAxmuPAZHDN2ggdVDiw3yg4CIEdYDEOFsnjcB3ok1AITWf3Ec5ymO1ngTFtwjXefuBh1wr4hkKBaeprzlL8YuR0YuLYmLdbQIfhYPOhv2HlxU=
